# Generated by Django 5.0.2 on 2024-03-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_friendshiprequest_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="total_games",
        ),
    ]
