# Generated by Django 5.0 on 2023-12-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChessGame",
            fields=[
                ("fen", models.CharField(max_length=255)),
                ("game_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
