# Generated by Django 5.0 on 2024-02-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chess_engine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Move',
        ),
    ]
