# Generated by Django 5.0.2 on 2024-04-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess_engine", "0003_botchessgame_is_finished_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botchessgame",
            name="winner",
            field=models.CharField(
                blank=True,
                help_text="Winner of the game (Bot or Player).",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="selfchessgame",
            name="winner",
            field=models.CharField(
                blank=True,
                help_text="Winner of the game (White or Black or Draw).",
                max_length=5,
                null=True,
            ),
        ),
    ]
