# Generated by Django 5.0.2 on 2024-04-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chess_engine", "0004_botchessgame_winner_alter_selfchessgame_winner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botchessgame",
            name="player",
        ),
        migrations.RemoveField(
            model_name="multiplayerchessgame",
            name="player",
        ),
    ]
