# Generated by Django 5.0.2 on 2024-04-14 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chess_engine", "0005_remove_botchessgame_player_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="botchessgame",
            name="player",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer account who played this game.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
